cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.cart_detail,
        name='cart_detail'),
    url(r'^remove/(?P<item_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
    url(r'^add/(?P<item_id>\d+)/$',
        views.cart_add,
        name='cart_add')
]

customer/urls.py
from django.conf.urls import url
from . import views

# Maybe no need to view customer
urlpatterns = [
    #url(r'^(?P<c_id>\d+)/$', views.customer_list, name = 'list'),
    url(r'^list$', views.customer_list, name = 'list'),
    url(r'^new$', views.customer_new, name = 'new'),
    url(r'^login$', views.customer_signIn, name='sign_in'),
    url(r'^register$', views.customer_signUp, name='sign_up'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls', namespace='shop')),						# Shopping page
    url(r'^customer/', include('customer.urls', namespace='customer')),		# Customer information
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    # url(r'^payment/', include('payment.urls', namespace='payment')),
]



#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

customer/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Customer(models.Model):
    customer_id = models.IntegerField(db_column='Customer Id', primary_key=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    email = models.CharField(db_column='Email', unique=True, max_length=45)  # Field name made lowercase.
    first_name = models.CharField(db_column='First Name', max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    last_name = models.CharField(db_column='Last Name', max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    phone_number = models.CharField(db_column='Phone Number', unique=True, max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    address = models.CharField(db_column='Address', max_length=45)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Customer'

    CUR_ID = 0

customer/forms.py
from django import forms

class LoginForm(forms.Form):
    c_id = forms.IntegerField(label='User ID', widget=forms.NumberInput)
    email = forms.EmailField(label='E-Mail', widget=forms.EmailInput)
    phone = forms.CharField(label='Phone #', widget=forms.TextInput)

    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)
class RegisterForm(forms.Form):
    c_id = forms.IntegerField(label='User ID', widget=forms.NumberInput)
    firstN = forms.CharField(label='First Name', widget=forms.TextInput)
    lastN = forms.CharField(label='Last Name', widget=forms.TextInput)
    email = forms.EmailField(label='E-Mail', widget=forms.EmailInput)
    phone = forms.CharField(label='Phone #', widget=forms.TextInput)
    address = forms.CharField(label='Address', widget=forms.TextInput)

    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

customer/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render
from .models import Customer
from .forms import LoginForm, RegisterForm

# Create your views here.
def customer_list(request):
    #customers = Customer.objects.all()
    form = LoginForm(request.POST)
    print(form.errors)
    if form.is_valid():
        cd = form.cleaned_data
        c_id = cd['c_id']
        Customer.CUR_ID = c_id
        #customer = get_object_or_404(Customer, customer_id = cd['c_id'])
    else:
        c_id = 0
        #customer = get_object_or_404(Customer, customer_id = 1)
    customer = get_object_or_404(Customer, customer_id = c_id)
    return render(request,
                  'customer/list.html',
                  {'customer': customer})

def customer_new(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        c_id = cd['c_id']
        c_first = cd['firstN']
        c_last = cd['lastN']
        c_email = cd['email']
        c_phone = cd['phone']
        c_addr = cd['address']
        Customer.CUR_ID = c_id
        customer = Customer.objects.create(customer_id=c_id,
                email=c_email,
                first_name=c_first,
                last_name=c_last,
                phone_number=c_phone,
                address=c_addr)
    return render(request,
                  'customer/list.html',
                  {'customer': customer})

def customer_signIn(request):
    loginForm = LoginForm()
    return render(request, 'customer/login.html', {'loginForm': LoginForm})

def customer_signUp(request):
    registerForm = RegisterForm()
    return render(request, 'customer/register.html', {'registerForm': RegisterForm})

customer/templates/customer/list.html
{% extends "shop/base.html" %}
{% load bootstrap3 %}
{% block title %}
    You
{% endblock %}

{% block content %}
   <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">E-Mail</th>
                    <th class="text-center">First Name</th>
                    <th class="text-center">Last Name</th>
                    <th class="text-center">Phone Number</th>
                    <th class="text-center">Address</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="col-sm-1 col-md-2 text-center"><strong>{{ customer.customer_id }}</strong></td>
                        <td class="col-sm-1 col-md-2 text-center"><strong>{{ customer.email }}</strong></td>
                        <td class="col-sm-1 col-md-2 text-center"><strong>{{ customer.first_name }}</strong></td>
                        <td class="col-sm-1 col-md-2 text-center"><strong>{{ customer.last_name }}</strong></td>
                        <td class="col-sm-1 col-md-2 text-center"><strong>{{ customer.phone_number }}</strong></td>
                        <td class="col-sm-1 col-md-2 text-center"><strong>{{ customer.address }}</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>
    <div class="col-sm-12 col-md-10 col-md-offset-5">
          {% buttons %}
            <button type="button" class="btn btn-success btn-product">
            Update
            </button>
        {% endbuttons %}
    </div>                  


{% endblock %}

customer/templates/customer/login.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Login{% endblock %}</title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<div class="container">
{% block content %}
<div class="page-header">
  <h2>Login</h2>
</div>

  <form  action="{% url "customer:list" %}" method="post">
    {% csrf_token %}
    {% bootstrap_form loginForm %}
    <p align="middle">
    <button type="submit">Login</button>
  </p>
  </form>
{% endblock %}
</div>
</body>
</html>

customer/templates/customer/register.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Login{% endblock %}</title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<div class="container">
{% block content %}
<div class="page-header">
  <h2>Register</h2>
</div>

  <form  action="{% url "customer:new" %}"  method="post">
    {% csrf_token %}
    {% bootstrap_form registerForm %}
    <p align="middle">
    <button type="submit">Create</button>
  </p>
  </form>
{% endblock %}
</div>
</body>
</html>