cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.cart_detail,
        name='cart_detail'),
    url(r'^remove/(?P<item_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
    url(r'^add/(?P<item_id>\d+)/$',
        views.cart_add,
        name='cart_add')
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls', namespace='shop')),						# Shopping page
    url(r'^customer/', include('customer.urls', namespace='customer')),		# Customer information
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    # url(r'^payment/', include('payment.urls', namespace='payment')),
]



#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

# Maybe no need to view customer
urlpatterns = [
    url(r'^ship$', views.shipment_view, name = 'shipment'),
    url(r'^shipAdd$', views.shipment_add, name = 'shipmentAdd'),
    url(r'^payment$', views.payment_view, name = 'payment'),
    url(r'^payAdd$', views.payment_add, name = 'paymentAdd'),
    #url(r'^detail$', views.order_view, name = 'order_detail'),
]

shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.inventory_list,
        name='inventory_list'),
    url(r'^(?P<item_id>\d+)/$',
        views.inventory_detail,
        name='inventory_detail')
    ]

cart/models.py
from __future__ import unicode_literals
from django.db import models
from shop.models import Inventory
from customer.models import Customer

class Item(models.Model):
    item_id = models.ForeignKey(Inventory, models.DO_NOTHING, db_column='Item Id', primary_key=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    price = models.IntegerField(db_column='Price')  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=45, blank=True, null=True)  # Field name made lowercase.
    seller = models.CharField(db_column='Seller', max_length=45)  # Field name made lowercase.
    customer_id = models.ForeignKey(Customer, models.DO_NOTHING, db_column='Customer Id')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    quantity_per_item = models.IntegerField(db_column='Quantity per Item')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    total_price = models.IntegerField(db_column='Total_Price')  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = 'Item'
        unique_together = (('item_id', 'customer_id'),)

cart/forms.py
from django import forms
from .models import Item
from shop.models import Inventory

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
	# def __init__(self, target_id=20):
	# 	try:
	# 		quantity_per = Inventory.objects.get(item_id=target_id).quantity
	# 		print('################################')
	# 		print('Succeed Parse')
	# 		print(quantity_per)
	# 		QUANTITY_CHOICES = [(i, str(i)) for i in range(1, quantity_per+1)]
	# 		quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, 
	# 									  	  coerce=int)
	# 		update = forms.BooleanField(required=False,
	# 							initial=False,
	# 							widget=forms.HiddenInput)
	# 	except:
	# 		print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
	# 		print('Fail parse')
	# 		pass
	#quantity_per = Item.objects.get(item_id=target_id).quantity_per_item
	#PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, quantity_per+1)]
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, 
									  coerce=int)
	update = forms.BooleanField(required=False,
								initial=False,
								widget=forms.HiddenInput)

	def match_quantity(self, target_id=20):
		try:
			quantity_per = Inventory.objects.get(item_id=target_id).quantity
			print('################################')
			print('Succeed Parse')
			print(quantity_per)
			QUANTITY_CHOICES = [(i, str(i)) for i in range(1, quantity_per+1)]
			quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, 
										  	  coerce=int)
		except:
			print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
			print('Fail parse')
			pass

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.exceptions import ObjectDoesNotExist

from shop.models import Inventory
#from .cart import Cart
from .forms import CartAddProductForm
from customer.models import Customer
from .models import Item

@require_POST
def cart_add(request, item_id):
    product = get_object_or_404(Inventory, item_id=item_id)
    customer = get_object_or_404(Customer, customer_id=Customer.CUR_ID)
    form = CartAddProductForm(request.POST)#.__init__(target_id=product)
    form.match_quantity(item_id)            # for matching quantity
    if form.is_valid():
        cd = form.cleaned_data
        try:
            Item.objects.filter(item_id=item_id).update(quantity_per_item= cd['quantity'])
            per_price = Item.objects.get(item_id=item_id).price
            Item.objects.filter(item_id=item_id).update(total_price = per_price * cd['quantity'])
        except ObjectDoesNotExist:
            Item.objects.create(item_id=product,
                                price=product.price,
                                type=product.type,
                                seller=product.seller,
                                customer_id=customer,
                                quantity_per_item=cd['quantity'],
                                total_price = product.price * cd['quantity'])

    return redirect('cart:cart_detail')


def cart_remove(request, item_id):
    product = get_object_or_404(Inventory, item_id=item_id)
    try:
        Item.objects.filter(item_id=product).delete()
    except ObjectDoesNotExist:
        pass

    return redirect('cart:cart_detail')


def cart_detail(request):
    print(Customer.CUR_ID)
    items = Item.objects.filter(customer_id=Customer.CUR_ID)
    """
    for item in items:
        inventory = item.item_id
    """
    """
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    """
    return render(request, 'cart/detail.html', {'items': items})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
   <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="text-center">Product</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Total</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>
                {% for item in items %}
                <tr>
                    <td class="col-sm-1 col-md-3 text-center"><strong>{{ item.item_id.item_name }}</strong></td>
                    <td class="col-sm-1 col-md-1 text-center"><strong>{{ item.quantity_per_item }}</strong>
                        <a href="{% url "shop:inventory_detail" item.item_id.item_id %}">
                            {% csrf_token %}
                            {% buttons %}
                                <button type="submit" class="btn btn-success btn-product">
                                    <span class="glyphicon glyphicon-shopping-cart"></span> Update
                                </button>
                            {% endbuttons %}
                        </a>                        
                    </td>
                    <td class="col-sm-1 col-md-3 text-center"><strong>${{ item.price }}</strong></td>
                    <td class="col-sm-1 col-md-3 text-center"><strong>${{ item.total_price }}</strong></td>
                    <td class="col-sm-1 col-md-1" style="text-align: center">
                        <a href="{% url "cart:cart_remove" item.item_id.item_id %}" class="btn btn-danger">
                            <i class="glyphicon glyphicon-remove" aria-hidden="true"></i> Remove
                        </a>
                        
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-sm-12 col-md-10 col-md-offset-5">
          {% buttons %}
            <button type="button" class="btn btn-success btn-product">
                <a href="{% url "orders:shipment" %}">
                    Check
                </a>
            </button>
        {% endbuttons %}
    </div> 

{% endblock %}