cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.cart_detail,
        name='cart_detail'),
    url(r'^remove/(?P<item_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
    url(r'^add/(?P<item_id>\d+)/$',
        views.cart_add,
        name='cart_add')
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls', namespace='shop')),						# Shopping page
    url(r'^customer/', include('customer.urls', namespace='customer')),		# Customer information
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    # url(r'^payment/', include('payment.urls', namespace='payment')),
]



#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

# Maybe no need to view customer
urlpatterns = [
    url(r'^ship$', views.shipment_view, name = 'shipment'),
    url(r'^shipAdd$', views.shipment_add, name = 'shipmentAdd'),
    url(r'^payment$', views.payment_view, name = 'payment'),
    url(r'^payAdd$', views.payment_add, name = 'paymentAdd'),
    #url(r'^detail$', views.order_view, name = 'order_detail'),
]

orders/models.py
from django.db import models
from cart.models import Item
from customer.models import Customer

# Create your models here.
"""
class ShoppingCart(models.Model):
    customer_id = models.ForeignKey(Item, models.DO_NOTHING, db_column='Customer Id')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    item_name = models.CharField(db_column='Item Name', max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    quantity_per_item = models.IntegerField(db_column='Quantity per Item')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    price_per_item = models.IntegerField(db_column='Price per Item')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    item_id = models.ForeignKey(Item, models.DO_NOTHING, db_column='Item Id')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    shopping_cart_id = models.IntegerField(db_column='Shopping Cart Id', primary_key=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    purchased_date = models.DateTimeField(db_column='Purchased Date')  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = 'Shopping Cart'
        unique_together = (('shopping_cart_id', 'item_id'),)
"""

class Payment(models.Model):
    customer_id = models.ForeignKey(Customer, models.DO_NOTHING, db_column='Customer Id', primary_key=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    card_number = models.CharField(db_column='Card Number', max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    card_expire_date = models.DateTimeField(db_column='Card Expire Date')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    payment_type = models.CharField(db_column='Payment Type', max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = 'Payment'
        unique_together = (('customer_id', 'card_number'),)


class Shipment(models.Model):
    physical_address = models.TextField(db_column='Physical Address')  # Field name made lowercase. Field renamed to remove unsuitable characters.
    shipment_type = models.CharField(db_column='Shipment Type', max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    shipment_detail = models.CharField(db_column='Shipment Detail', max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    customer_id = models.ForeignKey(Customer, models.DO_NOTHING, db_column='Customer Id', primary_key=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.

    class Meta:
        managed = False
        db_table = 'Shipment'
        unique_together = (('customer_id', 'shipment_detail'),)

orders/forms.py
from django import forms

class ShipForm(forms.Form):
    ship_type = forms.CharField(label='Shipment Type', widget=forms.TextInput)
    ship_detail = forms.CharField(label='Shipment Detail', widget=forms.TextInput)
    address = forms.CharField(label='Address', widget=forms.TextInput)

    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)
class PayForm(forms.Form):
    DATE_INPUT_FORMATS = ['%d-%m-%Y']
    pay_Type = forms.CharField(label='Payment Type', widget=forms.TextInput)
    card_num = forms.CharField(label='Card Number', widget=forms.TextInput)
    card_date = forms.DateField(label='Expire Date', widget=forms.DateInput,
            input_formats=DATE_INPUT_FORMATS)

    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.core.exceptions import ObjectDoesNotExist

from .forms import ShipForm, PayForm
from .models import Payment, Shipment
from customer.models import Customer
from shop.models import Inventory

# Create your views here.
# @require_POST

def shipment_view(request):
    shipForm = ShipForm()
    return render(request, 'orders/ship.html', {'ShipForm': ShipForm})

def payment_view(request):
    payForm = PayForm()
    return render(request, 'orders/pay.html', {'PayForm': PayForm})

def shipment_add(request):
    customer = get_object_or_404(Customer, customer_id=Customer.CUR_ID)
    try:
        Shipment.objects.get(customer_id=customer)
        return redirect('orders:payment')
    except ObjectDoesNotExist:
        form = ShipForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            c_type = cd['ship_type']
            c_detail = cd['ship_detail']
            c_address = cd['address']
            Shipment.objects.create(customer_id=customer,
                    physical_address=c_address,
                    shipment_type=c_type,
                    shipment_detail=c_detail)
            return redirect('orders:payment')


def payment_add(request):
    customer = get_object_or_404(Customer, customer_id=Customer.CUR_ID)
    try:
        Payment.objects.get(customer_id=customer)
        return render(request, 'orders/Thanks.html')
    except ObjectDoesNotExist:
        form = PayForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            c_id = customer
            c_type = cd['pay_Type']
            c_cardnum = cd['card_num']
            c_carddate = cd['card_date']
            Payment.objects.create(customer_id=c_id,
                    payment_type=c_type,
                    card_expire_date=c_carddate,
                    card_number=c_cardnum)
            return render(request, 'orders/Thanks.html')
            #inventories = Inventory.objects.all()
            #return render(request,'shop/list.html', {'inventories': inventories})

"""
def order_detail(request, customer_id):
    orders = ShoppingCart.objects.filter(customer_id=customer_id)
    return render(request, 'orders/detail.html', {'orders': orders})
"""

orders/templates/orders/Thanks.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Thanks{% endblock %}</title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<div class="container">
{% block content %}
<div class="page-header">
  <h2>Thanks</h2>
</div>
{% endblock %}
</div>
</body>
</html>

orders/templates/orders/detail.html
{% extends "shop/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
    Your Order
{% endblock %}

{% block content %}
   <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="text-center">Product</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Total</th>
                    <th class="text-center">Date</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>
                {% for item in orders %}
                <tr>
                    <td class="col-sm-1 col-md-3 text-center"><strong>{{ item.item_name }}</strong></td>
                    <td class="col-sm-1 col-md-1 text-center"><strong>{{ item.quantity_per_item }}</strong></td>
                    <td class="col-sm-1 col-md-3 text-center"><strong>${{ item.price_per_item }}</strong></td>
                    <td class="col-sm-1 col-md-3 text-center"><strong>${{ item.total_price }}</strong></td>
                    <td class="col-sm-1 col-md-3 text-center"><strong>${{ item.purchased_date }}</strong></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

orders/templates/orders/pay.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Payment{% endblock %}</title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<div class="container">
{% block content %}
<div class="page-header">
  <h2>Payment</h2>
</div>

  <form  action="{% url "order:detail" %}"  method="post">
    {% csrf_token %}
    {% bootstrap_form PayForm %}
    <p align="middle">
    <button type="submit">Next</button>
  </p>
  </form>
{% endblock %}
</div>
</body>
</html>

orders/templates/orders/ship.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Shipment{% endblock %}</title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<div class="container">
{% block content %}
<div class="page-header">
  <h2>Shipment</h2>
</div>

  <form  action="{% url "orders:shipmentAdd" %}"  method="post">
    {% csrf_token %}
    {% bootstrap_form ShipForm %}
    <p align="middle">
    <button type="submit">Next</button>
  </p>
  </form>
{% endblock %}
</div>
</body>
</html>