cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.cart_detail,
        name='cart_detail'),
    url(r'^remove/(?P<item_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
    url(r'^add/(?P<item_id>\d+)/$',
        views.cart_add,
        name='cart_add')
]

customer/urls.py
from django.conf.urls import url
from . import views

# Maybe no need to view customer
urlpatterns = [
    #url(r'^(?P<c_id>\d+)/$', views.customer_list, name = 'list'),
    url(r'^list$', views.customer_list, name = 'list'),
    url(r'^new$', views.customer_new, name = 'new'),
    url(r'^login$', views.customer_signIn, name='sign_in'),
    url(r'^register$', views.customer_signUp, name='sign_up'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls', namespace='shop')),						# Shopping page
    url(r'^customer/', include('customer.urls', namespace='customer')),		# Customer information
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    # url(r'^payment/', include('payment.urls', namespace='payment')),
]



#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL,
#                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.inventory_list,
        name='inventory_list'),
    url(r'^(?P<item_id>\d+)/$',
        views.inventory_detail,
        name='inventory_detail')
    ]

shop/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


class Inventory(models.Model):
    item_id = models.IntegerField(db_column='Item Id', primary_key=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    item_name = models.CharField(db_column='Item Name', max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    quantity = models.IntegerField(db_column='Quantity')  # Field name made lowercase.
    price = models.IntegerField(db_column='Price')  # Field name made lowercase.
    seller = models.CharField(db_column='Seller', max_length=45)  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=45, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Inventory'

    def get_absolute_url(self):
        return reverse('shop:inventory_detail', args=[self.item_id])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Inventory
from cart.forms import CartAddProductForm
from review.models import Review

def inventory_list(request):
    #inventories = Inventory.objects.filter(lambda x: x > 0, quantity)
    inventories = Inventory.objects.all()
    return render(request,
                  'shop/list.html',
                  {'inventories': inventories})
# Create your views here.

def inventory_detail(request, item_id):
    inventory = get_object_or_404(Inventory,
                                item_id=item_id)
    cart_product_form = CartAddProductForm()#.__init__(target_id=inventory)
    cart_product_form.match_quantity(item_id)     # for matching quantity

    reviews = Review.objects.filter(item_id=inventory)

    return render(request,
                  'shop/detail.html',
                  {'inventory': inventory,
                   'cart_product_form': cart_product_form,
                   'reviews': reviews})

shop/templates/shop/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<div class="container">
    <p align="right">
    <a href="{% url "customer:sign_in" %}">
    Sign-In
    </a>
     or
    <a href="{% url "customer:sign_up" %}">
    Sign-Up
    </a>
    </p>
    <div class="page-header">
        <a href="/"><h1>My shop</h1></a>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <p align="right">
            <a href="{% url "cart:cart_detail" %}">
                Your cart
            </a>
            </p>
        </div>
    </div>

    {% block content %}
    {% endblock %}
</div>
</body>
</html>

shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title %}
    Buy {{inventory.item_name}}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6 col-md-4">

            </div>
            <div class="col-md-6 col-md-4">
                <div class="thumbnail">
                    <!--
                    <img src="{% if product.image %}{{ product.image.url }}
                              {% else %}{% static "img/no_image.png" %}{% endif %}"
                         class="img-responsive">
                    -->
                    <img src="{% static "img/no_image.png" %}">
                    <div class="caption">
                        <div class="row">
                            <div class="col-md-9 col-xs-6">
                                <h3>{{ inventory.item_name }}</h3>
                            </div>
                            <div class="col-md-3 col-xs-6 price">
                                <h3>
                                    <label>${{ inventory.price }}</label></h3>
                            </div>
                        </div>

                        
                        <div class="row">
                            
                            {% if inventory.type %}
                            <div class="col-md-2 col-xs-6">
                                <h4>Type:</h4>
                            </div>
                            <div class="col-md-3 col-xs-6 price">
                                <h4>{{ inventory.type }}</h4>
                            </div>
                            {% else %}
                            <div class="col-md-5 col-xs-0">
                            </div>
                            {% endif %}
                            <div class="col-md-1 col-xs-0">
                            </div>
                            <div class="col-md-2 col-xs-6">
                                <h4>Seller:</h4>
                            </div>
                            <div class="col-md-3 col-xs-6 price">
                                <h4>{{ inventory.seller }}</h4>
                            </div>
                        </div>
                        
                      
                        <p></p>
                    </div>
                        <form action="{% url "cart:cart_add" inventory.item_id %}" method="post">
                            {% csrf_token %}
                            {% bootstrap_form cart_product_form%}
                            {% buttons %}
                                <button type="submit" class="btn btn-success btn-product">
                                    <span class="glyphicon glyphicon-shopping-cart"></span> Update to cart
                                </button>
                            {% endbuttons %}
                        </form>
                      
                        <h3> <font color="grey"> Review  </h3>

                        {% for review in reviews %}
                            <div class="row">
                                <div class="col-md-6 col-xs-6">
                                    <b> Ratings: {{ review.ratings }} </b>
                                </div>
                                <div class="col-md-6 col-xs-6">
                                    <p> Name: {{review.customer_id.first_name}} </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-1 col-xs-1">
                                </div>
                                <div class="col-md-10 col-xs-10">
                                    <p>{{ review.detailed_review }}</p>
                                </div>
                            </div>
                            
                        {% endfor %}  



                </div>
            </div>
            <div class="col-md-6 col-md-4">

            </div>
        </div>

    </div>


{% endblock %}

shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% load staticfiles %}

{% block title %}
        Inventories
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <h2>Products</h2>
            <div class="row">
                {% for inventory in inventories %}
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ inventory.get_absolute_url}}">
                            <img src="{% static "img/no_image.png" %}">
                            </a>
                            <a href="{{ inventory.get_absolute_url}}">
                                <b> {{inventory.item_name}} </b>
                            </a>
                            ${{ inventory.price }}
                        </div>
                    </div>
                {% endfor %}
            </div>


        </div>


    </div>
{% endblock %}